### ISSUE TITLE
2.29.18: VirtualDevices nicht gestartet

### ISSUE THREAD

**Issue by jp112sdl** [leonsio/YAHM#121]
Virtuelle Geräte (in der WebUI unter Einstellungen->Gruppen) sind nicht verfügbar.
Die Seite bleibt leer.
Es erscheint in der WebUI der Fehler, dass die Komponente "VirtualDevices" nicht reagiert.

**InterfacesList.xml:**
``` 
<ipc>
 <name>VirtualDevices</name>
 <url>xmlrpc://127.0.0.1:9292/groups</url> 
 <info>Virtual Devices</info> 
</ipc>
```

Port 9292 ist nicht erreichbar und auch nicht "existent".

```netstat -a | grep 9292``` bleibt leer

_Im Vergleich dazu sieht es bei einer **2.27.8** Installation so aus:_
```netstat -a | grep 9292```
tcp        0      0 :::9292                 :::*                    LISTEN      

Ich habe leider keinen Ansatz, von welchem Prozess dieser überhaupt bereitgestellt wird :/

**Comment by jp112sdl** [comment]
Soweit ich es bisher analysieren konnte, spielt die HMIPServer.jar eine Rolle.

**Ausgabe des Logs der HMIPServer.jar in CCU Version 2.27.8:**
```
Jul 19 11:10:12 de.eq3.cbcs.vertx.management.VertxManager INFO  [Thread-1] SYSTEM: added for deployment [BackendWorker] (1) *worker 
Jul 19 11:10:12 de.eq3.cbcs.vertx.management.VertxManager INFO  [Thread-1] SYSTEM: added for deployment [GroupRequestWorker] (1) *worker 
Jul 19 11:10:12 de.eq3.cbcs.vertx.management.VertxManager INFO  [Thread-1] SYSTEM: deploying 2 classes to Vert.x 
Jul 19 11:10:12 de.eq3.cbcs.vertx.management.VertxManager INFO  [Thread-1] SYSTEM: 2 VertxDeployers initialized 
Jul 19 11:10:12 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-4] SYSTEM: start of BackendWorker succeeded (deployment-65f74b8e-5262-4393-9ad3-7ae3aa04629c) 
Jul 19 11:10:12 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-3] SYSTEM: start of GroupRequestWorker succeeded (deployment-262173da-1aee-405d-b160-1af2a1a51d6a) 
Jul 19 11:10:12 de.eq3.cbcs.vertx.management.VertxManager INFO  [Thread-1] SYSTEM: initial deployment complete _____________________________________________________ 
Jul 19 11:10:12 de.eq3.ccu.server.HMServer INFO  [Thread-1] Starting HMServer at 127.0.0.1:9292 
Jul 19 11:10:12 de.eq3.ccu.server.HMServer INFO  [Thread-1] Read Configuration 
Jul 19 11:10:13 de.eq3.ccu.server.HMServer INFO  [Thread-1] Create Bidcos Dispatcher 
Jul 19 11:10:13 de.eq3.ccu.server.HMServer INFO  [Thread-1] InitBidCosCache 
```

...**fehlt** beim Starten der HMIPServer.jar in CCU Version **2.29.18** komplett :/

**Comment by jp112sdl** [comment]
**Der Start von HMServer schlägt fehl.**

```15:19:58,573 ERROR [de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization:error] () Error 'LOCAL_ADAPTER_NO_SUCH_PORT' while trying to open port '/dev/ttyS0':
de.eq3.cbcs.lib.commdevice.CommDeviceException: Exception while trying to open serial port. Check configured port '/dev/ttyS0'
	at de.eq3.cbcs.lib.nrjavaserialdevice.SerialCommDevice.open(SerialCommDevice.java:109)
	at de.eq3.cbcs.lib.hmiptrxcommadapter.HomeMaticIPTRXCommAdapter.open(HomeMaticIPTRXCommAdapter.java:716)
	at de.eq3.cbcs.lib.hmiptrxcommadapter.HomeMaticIPTRXCommAdapter.<init>(HomeMaticIPTRXCommAdapter.java:85)
	at de.eq3.cbcs.server.local.base.internal.ShareableHomeMaticIPTRXCommAdapter.<init>(ShareableHomeMaticIPTRXCommAdapter.java:25)
	at de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization.start(LocalServerAdapterInitialization.java:171)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
Caused by: gnu.io.NoSuchPortException
	at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:294)
	at de.eq3.cbcs.lib.nrjavaserialdevice.SerialCommDevice.open(SerialCommDevice.java:100)
	... 12 more
```

**Comment by leonsio** [comment]
Es scheint als habe eq3 da etwas geändert :(
Vorher ging der dienst hoch ohne der Datei/Device

Die Datei kommt von homematic-ip module

**Comment by jp112sdl** [comment]
Wenn ich die ejre1.7.0_10 ins /opt kopiere und damit die HMIPServer.jar von 2.27.8 starte, gehts.
Kommt zwar auch ein Fehler, aber der HMServer wird dennoch gestartet.

Und was machen wir nu? :/ 

In RaspberryMatic muss das ja auch (irgendwann) mal funktionieren. Ist ja dieselbe Hardware-Basis... Oder bin ich auf dem Holzweg?

**Comment by leonsio** [comment]
Du kannst homematic ip Modul installieren. Dann wird es gehen
Ggf auch mit dummy device
Ist bei dir /dev/ttys0 vorhanden?

**Comment by jp112sdl** [comment]
Ich hatte das homematic-ip Modul gar nicht deinstalliert.

Wenn ich in der crRFD.conf aus ttyS0 ein ttyS1 mache (oder was auch immer), bleibt der Fehler immer derselbe.

Mein /dev sieht so aus:

```
/dev # ls -l /dev/tty*
crw-rw-rw-    1 root     tty         5,   0 Jul 19 13:15 /dev/tty
crw--w----    1 root     tty         4,   0 Jul 19 13:15 /dev/tty0
crw--w----    1 root     root      136,   1 Jul 19 13:21 /dev/tty1
crw-rw-rw-    1 root     root      204,  64 Jul 19 08:54 /dev/ttyAMA0
crw-rw-rw-    1 root     root        4,  64 Jul 19 08:41 /dev/ttyS0
-rw-r--r--    1 root     root             2 Jul 19 13:18 /dev/ttyS1
```

Ich teste gerade auf einem Pine64 ohne Funkmodul. 
Ging ja auch alles mit der 2.27.8... 

Dann habe ich auf meinem produktiven RasPi gestern die 2.29.18 versucht, aber da kommt das gleiche.

Was meinst du mit Dummy Device? 
Von dem ganzen /dev-Zeug hab ich nicht sooo den Plan :)

**Comment by jp112sdl** [comment]
So... Jetzt habe ich es geschafft, dass der HMIPServer mit /dev/console kommuniziert und der Fehler ```Exception while trying to open serial port``` tritt nicht mehr auf!

```
22:54:21,921 INFO  [gnu.io.CommPortIdentifier:<clinit>] () CommPortIdentifier:static initialization(), OS: Linux, arch: arm
22:54:21,922 INFO  [gnu.io.CommPortIdentifier:<clinit>] () Load the driver.
22:54:21,932 INFO  [gnu.io.RXTXCommDriver:<clinit>] () RXTXCommDriver : static initializer.
22:54:21,933 INFO  [de.eq3.cbcs.vertx.management.VertxManager:info] () SYSTEM: start of LegacyAPIWorker succeeded (7c2fc004-426d-4850-b5ee-df7bbbf43f25)
22:54:21,936 INFO  [gnu.io.SerialManager:<init>] () Load native library.
22:54:21,967 INFO  [gnu.io.CommPortIdentifier:getPortIdentifiers] () static CommPortIdentifier:getPortIdentifiers()
22:54:21,968 INFO  [gnu.io.RXTXCommDriver:initialize] () RXTXCommDriver:initialize(), osName: Linux
22:54:21,970 DEBUG [gnu.io.RXTXCommDriver:addSpecifiedPorts] () 
RXTXCommDriver:addSpecifiedPorts()
RXTX Warning:  Removing stale lock file. /var/lock/LCK..console
22:54:21,977 INFO  [gnu.io.RXTXCommDriver:initialize] () RXTXCommDriver:initialize(), osName: Linux
22:54:21,979 DEBUG [gnu.io.RXTXCommDriver:addSpecifiedPorts] () 
RXTXCommDriver:addSpecifiedPorts()
22:54:21,981 INFO  [gnu.io.RXTXCommDriver:getCommPort] () RXTXCommDriver:getCommPort(/dev/console,1)
22:54:22,030 DEBUG [de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization:debug] () Identify application
22:54:22,035 DEBUG [de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization:debug] () Added HMIP Adapter
22:54:22,037 INFO  [de.eq3.cbcs.vertx.management.VertxManager:info] () SYSTEM: start of LocalServerAdapterInitialization succeeded (adc36405-5ebb-4ca2-bf88-9a46845153fe)
```
Dann ist jedoch schluss - es passiert dann nicht mehr.

Ich habe mal die Ausgabe beim Starten des HMIPServer auf der originalen CCU2 getracet:

```
23:03:59,393 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Received adapter response for transaction ID 0
23:03:59,438 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Received adapter response for transaction ID 1
23:03:59,444 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () TRX adapter state: HMIP_TRX_App
23:03:59,450 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () TRX adapter application is already running
23:03:59,455 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () No NWK, try to set address ...
23:03:59,495 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Received adapter response for transaction ID 6
23:03:59,503 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () Set max send attempts for 3014F711A00003556990B1DF to 3
23:03:59,534 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Received adapter response for transaction ID 7
23:03:59,585 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Received adapter response for transaction ID 8
23:03:59,590 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () Application version 2.8.5
23:03:59,594 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () Bootloader version 1.0.5
23:03:59,598 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () hmos version 1.20.2
23:03:59,732 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Received adapter response for transaction ID 9
23:03:59,738 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () MCU type: ATmega644pa_AVR
23:03:59,779 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Received adapter response for transaction ID 10
23:03:59,797 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () Duty Cycle: 1.0
23:03:59,814 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () set DutyCycle limit to ffffffc8
23:03:59,929 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Received adapter response for transaction ID 11
23:03:59,943 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () Set Duty Cycle Limit
23:03:59,978 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Received adapter response for transaction ID 12
23:03:59,985 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () Current Security Counter: 371752607
23:03:59,990 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Access point exchanged or exists => Check security counter ...
23:03:59,995 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () time difference: 96332639994; current: 1500498239994; firstConnect: 1404165600000; offset: 50644468
23:04:00,001 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () Update security counter to calculation: 371753268
23:04:00,035 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Received adapter response for transaction ID 14
23:04:01,983 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Received adapter response for transaction ID 16
23:04:02,022 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Received adapter response for transaction ID 13
23:04:02,027 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () TRX adapter has no linkpartner
23:04:02,043 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Add or load Adapter to global Map
23:04:02,060 DEBUG [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:debug] () Initialize listener
23:04:02,263 INFO  [de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener:info] () Adapter with Access Point id 3014F711A00003556990B1DF initialized
23:04:02,323 INFO  [de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization:info] () HMIPTRXInitialResponseListener said that Adapter was initialized
```

Demnach findet ein serieller Datenaustausch mit dem Funkmodul statt und erst wenn das erfolgreich abgearbeitet ist, wird auch der VirtualDevices Service gestartet. :/ 

Es wird also nur funktionieren, wenn HmIP vollständig in YAHM integriert ist!?

Leider komme ich an der Stelle jetzt nicht mehr weiter, was das Anlegen von Loop-Devices etc. betrifft. :(

**Comment by leonsio** [comment]
Man kann zur Not ja eine ältere hmipserver Version nehmen ;)

**Comment by jp112sdl** [comment]
Nach vielem Lesen und Versuchen, habe ich nun folgenden Stand:

1.) homematic-ip modul ist aktiviert.
2.) multimacd und rfd laufen, es kommen auch von beiden ordentliche Debug-Ausgaben.
3.) Das Firmware-Update des Funkmoduls hat auch geklappt.
4.) multimacd hat folgende ```dmesg```-Ausgabe produziert:
```
[  800.254643] eq3loop: created slave ttyS0
[  800.258260] eq3loop: created slave mmd_bidcos
[  843.423550] eq3loop: eq3loop_open_slave() mmd_bidcos
```

/dev sieht nun wie folgt aus:
```
crw-------    1 root     root      241,   0 Jul 22 11:15 bcm2835-raw-uart
lrwxrwxrwx    1 root     root            28 Jul 21 13:58 ccu2-ic200 -> /sys/class/gpio/gpio18/value
drwxr-xr-x    2 root     root          4096 Jul 22 11:25 char
crw-------    1 root     tty       136,   3 Jul 22 11:18 console
crw-------    1 root     root      242,   0 Jul 22 11:15 eq3loop
lrwxrwxrwx    1 root     root            13 Jul 22 11:15 fd -> /proc/self/fd
lrwxrwxrwx    1 root     root             7 Jul 22 11:14 kmsg -> console
lrwxrwxrwx    1 root     root            10 Jul 21 13:12 log -> ../tmp/log
crw-------    1 root     root      242,   2 Jul 22 11:27 mmd_bidcos
crw-rw-rw-    1 root     root        1,   3 Jul 22 11:15 null
lrwxrwxrwx    1 root     root            13 Jul 21 13:01 ptmx -> /dev/pts/ptmx
drwxr-xr-x    2 root     root             0 Jul 22 11:14 pts
crw-rw-rw-    1 root     root        1,   8 Jul 22 11:15 random
drwxr-xr-x    2 root     root          4096 Jul 21 13:01 shm
lrwxrwxrwx    1 root     root            15 Jul 22 11:15 stderr -> /proc/self/fd/2
lrwxrwxrwx    1 root     root            15 Jul 22 11:15 stdin -> /proc/self/fd/0
lrwxrwxrwx    1 root     root            15 Jul 22 11:15 stdout -> /proc/self/fd/1
crw-rw-rw-    1 root     tty         5,   0 Jul 22 11:15 tty
crw--w----    1 root     tty         4,   0 Jul 22 11:15 tty0
crw--w----    1 root     root      136,   2 Jul 22 11:18 tty1
crw-------    1 root     root      204,  64 Jul 22 11:15 ttyAMA0
crw-r-----    1 root     root        4,  64 Jul 22 11:26 ttyS0
crw-rw-rw-    1 root     root        1,   9 Jul 22 11:15 urandom
crw-rw-rw-    1 root     root        1,   5 Jul 22 11:15 zero
```


Die Exception beim Start der HMIPServer.jar bleibt jedoch weiterhin bestehen.
```
Exception while trying to open serial port. Check configured port '/dev/ttyS0
```

**Comment by jp112sdl** [comment]
Habe die multimac.conf geändert, so dass das Gerät ```/dev/ttyS1``` angelegt wird und in der crRFD.conf habe ich ebenfalls den Adapter auf ```/dev/ttyS1``` geändert.

Nun läuft alles.
