### ISSUE TITLE
Error io.vertx.core.impl.BlockedThreadChecker

### ISSUE THREAD

**Issue by Sschhsd** [leonsio/YAHM#151]
Im Issue #149 habe ich beschrieben, dass meine Log-Datei nicht mehr gefüllt wird.
Nun ist mir aufgefallen, dass im Log dauerhaft die Exception geworfen wird:

	Nov 20, 2017 6:34:47 AM io.vertx.core.impl.BlockedThreadChecker

	WARNING: Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 7917 ms, time limit is 2000

	io.vertx.core.VertxException: Thread blocked

	at sun.misc.Unsafe.park(Native Method)

	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)

	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)

	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)

	at de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega.registerCallback(VirtualDeviceHandlerRega.java:97)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.AnnotationAwareRpcHandler.execute(AnnotationAwareRpcHandler.java:85)

	at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:70)

	at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:24)

	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)

	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)

	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:503)

	at io.vertx.core.eventbus.impl.EventBusImpl$$Lambda$36/12898656.handle(Unknown Source)

	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)

	at io.vertx.core.impl.ContextImpl$$Lambda$21/32711901.run(Unknown Source)

	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)

	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)

	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)

	at java.lang.Thread.run(Thread.java:745)

Wodruch entsteht dieser Fehler?

[yahm_console.log](https://github.com/leonsio/YAHM/files/1486553/yahm_console.log)

**Comment by leonsio** [comment]
das ist ein Problem der CCU und nicht von yahm ;)

**Comment by Sschhsd** [comment]
Hi leonsio,

ok und danke :)!
