### ISSUE TITLE
failed at first install

### ISSUE THREAD

**Issue by SirWesthoff** [leonsio/YAHM#170]
my hardware is a raspberry pi 3 modell b with debian stretch lite installed, openhab2 already running.  

*** make modules_prepare
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --silentoldconfig Kconfig
.config:803:warning: symbol value 'm' invalid for NF_CT_PROTO_DCCP
.config:805:warning: symbol value 'm' invalid for NF_CT_PROTO_SCTP
.config:806:warning: symbol value 'm' invalid for NF_CT_PROTO_UDPLITE
.config:823:warning: symbol value 'm' invalid for NF_NAT_PROTO_DCCP
.config:824:warning: symbol value 'm' invalid for NF_NAT_PROTO_UDPLITE
.config:825:warning: symbol value 'm' invalid for NF_NAT_PROTO_SCTP
*
* Restart config...
*
*
* IRQ subsystem
*
Expose hardware/virtual IRQ mapping via debugfs (IRQ_DOMAIN_DEBUG) [N/y/?] n
Expose irq internals in debugfs (GENERIC_IRQ_DEBUGFS) [N/y/?] (NEW) aborted!

Console input/output is redirected. Run 'make oldconfig' to update configuration.

scripts/kconfig/Makefile:38: recipe for target 'silentoldconfig' failed
make[2]: *** [silentoldconfig] Error 1
Makefile:544: recipe for target 'silentoldconfig' failed
make[1]: *** [silentoldconfig] Error 2
make: *** No rule to make target 'modules_prepare'.  Stop.
Traceback (most recent call last):
  File "/opt/YAHM/share/tools/rpi-source/rpi-source", line 379, in <module>
    sh("cd %s && make modules_prepare %s" % (linux_symlink, (" > /dev/null" if args.quiet else "")))
  File "/opt/YAHM/share/tools/rpi-source/rpi-source", line 85, in sh
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /usr/src/linux && make modules_prepare ' returned non-zero exit status 2
Blocking new kernel updates, please do not use rpi-update anymore, or run this module after kernel update again
Installing kernel modules
Building eq3 kernel modules
make -C /lib/modules/4.9.80-v7+/build M=/tmp/tmp.EPCexVQm5I/kernel modules
make[1]: Entering directory '/usr/src/linux-80a14a56dacb7cc2b40d5f37d00bedb0ceace130'

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

  CC [M]  /tmp/tmp.EPCexVQm5I/kernel/eq3_char_loop.o
In file included from <command-line>:0:0:
././include/linux/kconfig.h:5:32: fatal error: generated/autoconf.h: No such file or directory
 #include <generated/autoconf.h>
                                ^
compilation terminated.
scripts/Makefile.build:326: recipe for target '/tmp/tmp.EPCexVQm5I/kernel/eq3_char_loop.o' failed
make[2]: *** [/tmp/tmp.EPCexVQm5I/kernel/eq3_char_loop.o] Error 1
Makefile:1508: recipe for target '_module_/tmp/tmp.EPCexVQm5I/kernel' failed
make[1]: *** [_module_/tmp/tmp.EPCexVQm5I/kernel] Error 2
make[1]: Leaving directory '/usr/src/linux-80a14a56dacb7cc2b40d5f37d00bedb0ceace130'
Makefile:16: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: Problem while building eq3 module, exit

**Comment by leonsio** [comment]
Nutzt du Standard Treiber oder eins über rpi-update?

Gruß 

Leo

Von meinem iPhone gesendet

**Comment by SirWesthoff** [comment]
Wie meinst du das?  Ich habe openhab2 installiert und die addons. Und versucht yahm via quickinstall zu installieren.

 

Gruß 

 

Marcel

 

Von: Leonid Kogan <notifications@github.com> 
Gesendet: Donnerstag, 15. März 2018 09:56
An: leonsio/YAHM <YAHM@noreply.github.com>
Cc: heartsaver1859 <marcel.westhoff92@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [leonsio/YAHM] failed at first install (#170)

 

Nutzt du Standard Treiber oder eins über rpi-update? 

Gruß 

Leo 

Von meinem iPhone gesendet

**Comment by leonsio** [comment]
Das Problem ist der verwendete Linux Kernel 
Es kann mein Modul dagegen gebaut werden

Daher meine Frage. Hat nix mit openhab zu tun

Von meinem iPhone gesendet

**Comment by SirWesthoff** [comment]
Nein ich habe nur nach der Installation einmal apt update && apt upgrade -y laufen lassen. Wie kann ich das Kernel Problem denn umgehen? 


Von meinem Samsung Galaxy Smartphone gesendet.
null

**Comment by leonsio** [comment]
Hi

Probier mal

rm -rf /usr/src/linux*

Und führe die Installation erneut aus, bei Fragen einfach Y bzw. J eingeben und Enter drucken.

Falls es nicht klappt, dann mit rpi-update auf neuen Kernel gehen (reboot notwendig) und dann nochmal probieren.

Gruß

Leo

**Comment by heartsaver1859** [comment]
Ok erstmal danke. Das hat funktioniert. Aber jetzt gehe ich auf die IP und bekomme das angezeigt: 
Die Homematic CCU2 ist noch nicht bereit

Bitte warten. Sie werden automatisch auf die Startseite weitergeleitet.

ist das normal? Dauert das so lange bis das bereit ist?
